[platformio]
default_envs = parking_2node_node1

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_port = COM5
lib_compat_mode = strict
lib_deps =
    marvinroger/AsyncMqttClient @ ^0.9.0
    ESP32Async/AsyncTCP @ 3.3.2
    bblanchon/ArduinoJson @ ^7.4.3
lib_ignore =
    ESPAsyncTCP

[env:parking_2node_node1]
build_flags =
    -D PARKING_TOPOLOGY=2
    -D PARKING_NODE_ID=1

[env:parking_2node_node2]
build_flags =
    -D PARKING_TOPOLOGY=2
    -D PARKING_NODE_ID=2

[env:parking_3node_node1]
build_flags =
    -D PARKING_TOPOLOGY=3
    -D PARKING_NODE_ID=1

[env:parking_3node_node2]
build_flags =
    -D PARKING_TOPOLOGY=3
    -D PARKING_NODE_ID=2

[env:parking_3node_node3]
build_flags =
    -D PARKING_TOPOLOGY=3
    -D PARKING_NODE_ID=3
